# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

api_key = app_store_connect_api_key(
  key_id: "FXXUALYK6F",
  issuer_id: "69a6de7f-1ffd-47e3-e053-5b8c7c11a4d1",
  key_filepath: "./fastlane/AuthKey_FXXUALYK6F.p8"
)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    test_cases = [
      "Generate Screenshots/Generate_Screenshots/testScreenshots_ground",
      "Generate Screenshots/Generate_Screenshots/testScreenshots_ipEarly",
      "Generate Screenshots/Generate_Screenshots/testScreenshots_ip",
      "Generate Screenshots/Generate_Screenshots/testScreenshots_ipLate",
      "Generate Screenshots/Generate_Screenshots/testScreenshots_postIP"
    ]

    # Screenshots will be cleared via the Snapfile settings

    test_cases.each_with_index do |test_method, index|
      capture_screenshots(
        scheme: "Generate Screenshots",
        devices: [
          "iPhone 16 Pro Max",
          "iPhone 14 Plus",
          "iPad Pro 13-inch (M4)"
        ],
        languages: ["en-US"],
        output_directory: "./fastlane/screenshots",
        clear_previous_screenshots: false,
        override_status_bar: false,
        erase_simulator: true,
        only_testing: [test_method],
        reinstall_app: true,
        output_simulator_logs: true,
        headless: true,
        number_of_retries: 1,
        stop_after_first_error: true,
        result_bundle: false,
        concurrent_simulators: true
      )
    end

    upload_to_app_store
  end

  desc "Release new version"
  lane :release do
    build_app(scheme: "IP Inbound")
    send_build_to_bugsnag
    upload_symbols_to_bugsnag
  end
end
