name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: Unit Tests
    strategy:
      fail-fast: false
      matrix:
        macos: [macos-latest]
        ios: [18.1, 18.2]
        xcode: [latest-stable]
    runs-on: ${{ matrix.macos }}
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: actions/checkout@v4
      - name: Enable macros
        run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Run unit tests
        run: xcodebuild test -scheme "IP Inbound" -testPlan "Unit Tests" -destination "platform=iOS Simulator,name=iPhone 16 Pro,OS=${{ matrix.ios }}" | xcpretty && exit ${PIPESTATUS[0]}
